Repository htop-dev/htop, pull requests merged in 2020-10, with the labels that each got.

#188 Add security attribute process column
  linux/LinuxProcess.c
  linux/LinuxProcess.h
  linux/LinuxProcessList.c
Labels: RFE

#135 Add DiskIOMeter for IO read/write usage
  CRT.c
  CRT.h
  DiskIOMeter.c
  DiskIOMeter.h
  Makefile.am
  darwin/Platform.c
  darwin/Platform.h
  dragonflybsd/Platform.c
  dragonflybsd/Platform.h
  freebsd/Platform.c
  freebsd/Platform.h
  linux/Platform.c
  linux/Platform.h
  openbsd/Platform.c
  openbsd/Platform.h
  solaris/Platform.c
  solaris/Platform.h
  unsupported/Platform.c
  unsupported/Platform.h
Labels: RFE

#159 Add a date and datetime meter
  CRT.c
  CRT.h
  DateMeter.c
  DateMeter.h
  DateTimeMeter.c
  DateTimeMeter.h
  Makefile.am
  darwin/Platform.c
  dragonflybsd/Platform.c
  freebsd/Platform.c
  linux/Platform.c
  openbsd/Platform.c
  solaris/Platform.c
  unsupported/Platform.c
Labels: RFE

#189 Simplify statm parsing and document unused fields
  linux/LinuxProcess.c
  linux/LinuxProcessList.c
Labels: code quality :recycle:

#214 Add key to pause process list updates
  Action.c
  Action.h
  AffinityPanel.c
  AvailableMetersPanel.c
  CRT.c
  CRT.h
  ColorsPanel.c
  FunctionBar.c
  FunctionBar.h
  IncSet.c
  IncSet.h
  MainPanel.c
  MetersPanel.c
  ScreenManager.c
  ScreenManager.h
  htop.1.in
  htop.c
Labels: RFE

#131 Number CPUs from zero by default.
  DisplayOptionsPanel.c
  Settings.c
  Settings.h
Labels: default change
