Repository htop-dev/htop, pull requests merged in 2020-09, with the labels that each got.

#120 Drop always true condition
  linux/Platform.c
Labels: code quality

#134 Use PROCDIR throughout instead of /proc on Linux
  linux/LinuxProcessList.c
  linux/Platform.c
Labels: code quality :recycle:

#133 autotools: enable warnings and cleanup
  Makefile.am
  autogen.sh
  configure.ac
Labels: build system :wrench:

#122 Reorder check to avoid crash on invalid process field setting
  Settings.c
Labels: bug :bug:

#114 Add Linux process column for total context switches
  htop.1.in
  linux/LinuxProcess.c
  linux/LinuxProcess.h
  linux/LinuxProcessList.c
Labels: RFE

#109 Avoid unsigned integer overflow
  linux/LinuxProcessList.c
Labels: code quality :recycle:

#121 Avoid modifying optarg
  htop.c
Labels: bug :bug:, code quality :recycle:

#117 Call character checking function with unsigned char
  AvailableColumnsPanel.c
  CategoriesPanel.c
  ColumnsPanel.c
  IncSet.c
  MainPanel.c
  Panel.c
Labels: code quality :recycle:

#167 Use checked allocation wrappers
  linux/LinuxProcessList.c
Labels: code quality :recycle:

#148 Drop dead code after break
  solaris/SolarisProcess.c
Labels: code quality :recycle:, needs-discussion :thinking:

#152 Drop dead process fields
  Process.h
Labels: code quality :recycle:

#56 align cpu id to right
  CPUMeter.c
Labels: needs-discussion :thinking:

#67 use separate window/screen to show long commands in multiple lines
  Action.c
  CommandScreen.c
  CommandScreen.h
  Makefile.am
  htop.1.in
Labels: RFE

#107 Make --enable-hwloc and --enable-linux-affinity mutual exclusive
  .github/workflows/ci.yml
  Affinity.h
  configure.ac
Labels: build system :wrench:
