Repository htop-dev/htop, pull requests merged in 2021-03, with the labels that each got.

#533 SysArchMeter: read os-release instead of running lsb-release
  SysArchMeter.c
Labels: enhancement

#551 Fix truncation of the intermediate strings in the SysArch meter
  SysArchMeter.c
Labels: enhancement

#559 Follow followed process when switching thread visibilities
  Action.c
  ProcessList.c
Labels: enhancement

#436 FreeBSD: add support for CPU frequency and temperature
  CPUMeter.c
  DisplayOptionsPanel.c
  Settings.c
  Settings.h
  configure.ac
  freebsd/FreeBSDProcessList.c
  freebsd/FreeBSDProcessList.h
  freebsd/Platform.c
Labels: FreeBSD :japanese_ogre:

#537 Use unsigned types for CPU counts and associated variables
  Affinity.c
  Affinity.h
  AffinityPanel.c
  AvailableMetersPanel.c
  CPUMeter.c
  Header.c
  Header.h
  Meter.c
  Meter.h
  ProcessList.h
  Settings.c
  Settings.h
  darwin/DarwinProcessList.c
  darwin/Platform.c
  darwin/Platform.h
  dragonflybsd/DragonFlyBSDProcessList.c
  dragonflybsd/Platform.c
  dragonflybsd/Platform.h
  freebsd/FreeBSDProcessList.c
  freebsd/Platform.c
  freebsd/Platform.h
  linux/LinuxProcessList.c
  linux/Platform.c
  linux/Platform.h
  openbsd/OpenBSDProcessList.c
  openbsd/Platform.c
  openbsd/Platform.h
  solaris/Platform.c
  solaris/Platform.h
  solaris/SolarisProcessList.c
  unsupported/Platform.c
  unsupported/Platform.h
Labels: code quality :recycle:

#570 Openbsd Update
  ProcessList.c
  ProcessList.h
  openbsd/OpenBSDProcess.h
  openbsd/OpenBSDProcessList.c
  openbsd/OpenBSDProcessList.h
  openbsd/Platform.c
Labels: BSD :blowfish:

#582 Linux: handle garbage in /proc/loadavg
  linux/Platform.c
Labels: Linux :penguin:, bug :bug:
