Repository htop-dev/htop, pull requests merged in 2021-09, with the labels that each got.

#758 Linux: rework disk-io parsing
  linux/Platform.c
Labels: bug :bug:, Linux :penguin:

#775 PCP: do not set exe to empty string
  pcp/PCPProcessList.c
Labels: bug :bug:, PCP

#777 Add a Process_printPercentage helper routine
  Process.c
  Process.h
  linux/LinuxProcess.c
Labels: code quality :recycle:

#781 Settings: set ok when reading configuration from sysconfdir
  Settings.c
Labels: bug :bug:

#787 CRT: close backup stderr file after reset
  CRT.c
Labels: bug :bug:

#790 MemorySwapMeter: align with CPU meter
  MemorySwapMeter.c
Labels: bug :bug:

#791 HeaderOptionsPanel: select the current not saved option
  HeaderOptionsPanel.c
Labels: bug :bug:

#795 Linux: recalculate LRS value
  linux/LinuxProcessList.c
Labels: bug :bug:

#779 Highlight percentages similar to large numbers
  Process.c
Labels: enhancement

#797 MainPanel: do not reset on disabled mouse events
  MainPanel.c
Labels: enhancement

#798 Header: do not let multi-column meters expand to empty neighbors
  CPUMeter.c
  Header.c
  MemorySwapMeter.c
  Meter.h
Labels: bug :bug:

#799 Update ReadMe
  README
Labels: documentation :open_book:

#630 Use libunwind for printing backtrace
  CRT.c
  configure.ac
Labels: enhancement, Linux :penguin:, FreeBSD :japanese_ogre:

#809 Document minimum versions for glibc and libcap
  README
Labels: documentation :open_book:

#807 Fix mouse wheel collision with autogroups nice adjustment
  CRT.h
Labels: bug :bug:

#810 Adjust Makefile.am macro definitions for older automake versions
  Makefile.am
Labels: build system :wrench:

#820 Adds a missing HAVE_GETMOUSE check.
  MainPanel.c
Labels: bug :bug:, NetBSD :flags:
