Repository htop-dev/htop, pull requests merged in 2021-08, with the labels that each got.

#656 Rework CPU counting
  .github/workflows/ci.yml
  Action.c
  Affinity.c
  Affinity.h
  AffinityPanel.c
  AvailableMetersPanel.c
  CPUMeter.c
  CommandLine.c
  LoadAverageMeter.c
  Process.c
  ProcessList.c
  ProcessList.h
  README
  TasksMeter.c
  UptimeMeter.c
  configure.ac
  darwin/DarwinProcessList.c
  darwin/DarwinProcessList.h
  darwin/Platform.c
  dragonflybsd/DragonFlyBSDProcessList.c
  dragonflybsd/DragonFlyBSDProcessList.h
  dragonflybsd/Platform.c
  freebsd/FreeBSDProcessList.c
  freebsd/FreeBSDProcessList.h
  freebsd/Platform.c
  linux/LibSensors.c
  linux/LibSensors.h
  linux/LinuxProcessList.c
  linux/LinuxProcessList.h
  linux/Platform.c
  openbsd/OpenBSDProcessList.c
  openbsd/OpenBSDProcessList.h
  openbsd/Platform.c
  pcp/PCPProcessList.c
  pcp/PCPProcessList.h
  solaris/Platform.c
  solaris/SolarisProcessList.c
  solaris/SolarisProcessList.h
  unsupported/UnsupportedProcessList.c
  unsupported/UnsupportedProcessList.h
Labels: enhancement

#718 NetBSD: Rework CPU counting.
  netbsd/NetBSDProcessList.c
  netbsd/NetBSDProcessList.h
  netbsd/Platform.c
Labels: NetBSD :flags:, enhancement

#725 configure: check for NaN compiler support
  configure.ac
Labels: build system :wrench:

#722 Add columns for process autogroup identifier and nice value
  htop.1.in
  linux/LinuxProcess.c
  linux/LinuxProcess.h
  linux/LinuxProcessList.c
  linux/LinuxProcessList.h
  linux/Platform.c
  linux/ProcessField.h
  pcp/PCPProcess.c
  pcp/PCPProcess.h
  pcp/PCPProcessList.c
  pcp/Platform.c
  pcp/Platform.h
  pcp/ProcessField.h
Labels: Linux :penguin:, new feature

#723 netbsd: Add support for DiskIOMeter
  netbsd/Platform.c
Labels: enhancement, NetBSD :flags:

#726 PCP: implement a missing piece for offline and hotplug CPUs
  pcp/PCPProcessList.c
Labels: new feature, PCP

#732 Linux: do not include zram devices in DiskIO
  linux/Platform.c
Labels: Linux :penguin:

#707 PCP: Dynamic columns
  Action.c
  AvailableColumnsPanel.c
  AvailableColumnsPanel.h
  AvailableMetersPanel.c
  CategoriesPanel.c
  ColumnsPanel.c
  ColumnsPanel.h
  CommandLine.c
  DynamicColumn.c
  DynamicColumn.h
  DynamicMeter.h
  Makefile.am
  Process.c
  Process.h
  ProcessList.c
  ProcessList.h
  Settings.c
  Settings.h
  darwin/DarwinProcessList.c
  darwin/DarwinProcessList.h
  darwin/Platform.h
  dragonflybsd/DragonFlyBSDProcessList.c
  dragonflybsd/DragonFlyBSDProcessList.h
  dragonflybsd/Platform.h
  freebsd/FreeBSDProcessList.c
  freebsd/FreeBSDProcessList.h
  freebsd/Platform.h
  linux/LinuxProcessList.c
  linux/LinuxProcessList.h
  linux/Platform.h
  netbsd/Platform.h
  openbsd/OpenBSDProcessList.c
  openbsd/OpenBSDProcessList.h
  openbsd/Platform.h
  pcp/PCPDynamicColumn.c
  pcp/PCPDynamicColumn.h
  pcp/PCPDynamicMeter.c
  pcp/PCPDynamicMeter.h
  pcp/PCPProcess.c
  pcp/PCPProcess.h
  pcp/PCPProcessList.c
  pcp/PCPProcessList.h
  pcp/Platform.c
  pcp/Platform.h
  pcp/columns/container
  pcp/columns/delayacct
  pcp/columns/fdcount
  pcp/columns/guest
  pcp/columns/memory
  pcp/columns/sched
  pcp/columns/swap
  pcp/columns/tcp
  pcp/columns/udp
  pcp/columns/wchan
  solaris/Platform.h
  solaris/SolarisProcessList.c
  solaris/SolarisProcessList.h
  unsupported/Platform.h
  unsupported/UnsupportedProcessList.c
Labels: new feature, PCP

#705 docs: updates and new manual page for pcp-htop
  .gitignore
  configure.ac
  htop.1.in
  pcp-htop.5.in
Labels: documentation :open_book:, PCP

#734 netbsd: Add NetworkIOMeter support
  netbsd/Platform.c
Labels: new feature, NetBSD :flags:

#738 TasksMeter: save some float casts
  TasksMeter.c
Labels: enhancement, code quality :recycle:

#724 Respect "Show custom thread names" setting update
  Process.c
  linux/LinuxProcessList.c
Labels: bug :bug:

#741 Reset the signal handlers at program exit
  CRT.c
  CRT.h
  CommandLine.c
Labels: bug :bug:, enhancement, code quality :recycle:

#742 Simplify Action_pickFromVector() width parameter usage
  Action.c
  linux/Platform.c
Labels: code quality :recycle:

#743 PCP: PCPMetric.[ch] Mdoule
  Makefile.am
  pcp/PCPDynamicColumn.c
  pcp/PCPDynamicColumn.h
  pcp/PCPDynamicMeter.c
  pcp/PCPDynamicMeter.h
  pcp/PCPMetric.c
  pcp/PCPMetric.h
  pcp/PCPProcess.c
  pcp/PCPProcess.h
  pcp/PCPProcessList.c
  pcp/Platform.c
  pcp/Platform.h
Labels: code quality :recycle:, PCP

#747 Coverity scan updates (minor)
  Action.c
  pcp/PCPDynamicColumn.c
  pcp/PCPProcessList.c
  pcp/Platform.c
  pcp/Platform.h
Labels: code quality :recycle:

#749 Spell out virtualized
  Action.c
Labels: enhancement

#728 Read settings after applying defaults
  Settings.c
Labels: enhancement, needs-rebase, needs-discussion :thinking:, default change

#445 Add ability to change the header format
  Action.c
  AvailableMetersPanel.c
  AvailableMetersPanel.h
  CategoriesPanel.c
  CategoriesPanel.h
  Header.c
  Header.h
  HeaderLayout.h
  HeaderOptionsPanel.c
  HeaderOptionsPanel.h
  Makefile.am
  MetersPanel.c
  Settings.c
  Settings.h
Labels: new feature

#697 Introduce versioned config files and config_reader_min_version
  Settings.c
  Settings.h
Labels: code quality :recycle:, new feature

#763 HeaderLayout: save special ID in configuration
  HeaderLayout.h
  Settings.c
Labels: enhancement, default change

#764 configure: resolve autotools 2.70 deprecation warnings
  configure.ac
Labels: build system :wrench:

#752 Fix macOS CPU time calculations
  darwin/DarwinProcess.c
  darwin/DarwinProcess.h
  darwin/DarwinProcessList.c
Labels: bug :bug:, MacOS :green_apple:
