Repository htop-dev/htop, pull requests merged in 2021-02, with the labels that each got.

#443 Cache stderr to be able to print assert messages
  CRT.c
  configure.ac
Labels: enhancement, needs-discussion :thinking:

#530 InfoScreen: Remove old lines before scanning again
  InfoScreen.c
Labels: bug :bug:

#531 Enable making with -ggdb3 on configure --enable-debug
  Makefile.am
  configure.ac
Labels: build system :wrench:

#532 Remove setuid
  .github/workflows/ci.yml
  CRT.c
  CRT.h
  ChangeLog
  EnvScreen.c
  Process.c
  README
  Settings.c
  TraceScreen.c
  configure.ac
Labels: code quality :recycle:
