Repository htop-dev/htop, pull requests merged in 2021-11, with the labels that each got.

#843 Tidy up process state handling
  Process.c
  Process.h
  darwin/DarwinProcess.c
  dragonflybsd/DragonFlyBSDProcessList.c
  freebsd/FreeBSDProcessList.c
  linux/LinuxProcessList.c
  netbsd/NetBSDProcessList.c
  openbsd/OpenBSDProcessList.c
  pcp/PCPProcessList.c
  solaris/SolarisProcessList.c
  unsupported/UnsupportedProcessList.c
Labels: code quality :recycle:

#867 Cleanup: Fix misc styleguide issues
  ColorsPanel.c
  Compat.c
  HeaderOptionsPanel.c
  InfoScreen.c
Labels: code quality :recycle:

#852 Linux: use proper way to detect kernel threads
  linux/LinuxProcess.h
  linux/LinuxProcessList.c
Labels: enhancement, Linux :penguin:

#873 Reduce allocation size of cp_time_n and cp_time_o on FreeBSD and DragonFlyBSD
  dragonflybsd/DragonFlyBSDProcessList.c
  freebsd/FreeBSDProcessList.c
Labels: FreeBSD :japanese_ogre:, BSD :blowfish:, NetBSD :flags:

#750 Add OFFSET column to OpenFilesScreen
  OpenFilesScreen.c
Labels: enhancement

#874 Add a fix to use gettimeofday if monotonic is not available.
  generic/gettime.c
Labels: enhancement, MacOS :green_apple:

#878 add github workflow to build release tarball
  .github/workflows/build_release.yml
Labels: enhancement, needs-discussion :thinking:, build system :wrench:
