Repository htop-dev/htop, pull requests merged in 2021-06, with the labels that each got.

#649 Linux: drop O_PATH usage and update process uid on change
  Process.c
  linux/LinuxProcessList.c
Labels: Linux :penguin:, bug :bug:

#652 Apply stale lib highlighting for EXE too
  Process.c
Labels: enhancement

#653 Do not install recommended packages by default for the CI
  .github/workflows/ci.yml
Labels: build system :wrench:

#654 Add a section on PRs for the style guide
  docs/styleguide.md
Labels: documentation :open_book:, needs-discussion :thinking:
