Repository htop-dev/htop, pull requests merged in 2021-12, with the labels that each got.

#882 Fix an issue where the last line is not cleared when a signal is received
  CRT.c
  CommandLine.c
Labels: enhancement

#885 CGroupUtils: avoid unsigned integer underflow
  linux/CGroupUtils.c
Labels: code quality :recycle:

#884 Process: highlight UNINTERRUPTIBLE_WAIT state (D)
  Process.c
Labels: enhancement

#865 Add option to change default signal sent on F9
  Action.c
  SignalsPanel.c
  SignalsPanel.h
Labels: needs-discussion :thinking:, new feature

#883 IOMeters: rework initial display
  DiskIOMeter.c
  Meter.h
  NetworkIOMeter.c
Labels: enhancement

#890 Linux: read generic sysfs batteries
  linux/Platform.c
Labels: bug :bug:, Linux :penguin:

#889 Screens update
  ScreensPanel.c
  Settings.c
  Settings.h
Labels: code quality :recycle:

#892 Hashmap: avoid rehashing to same size on shrinking
  Hashtable.c
Labels: enhancement

#895 configure: support libunwind of LLVM
  configure.ac
Labels: bug :bug:, build system :wrench:, Linux :penguin:

#897 LinuxProcessList: do not collect LRS per thread
  linux/LinuxProcessList.c
Labels: enhancement, Linux :penguin:

#898 GH Actions: enable Werror in PCP build
  .github/workflows/ci.yml
Labels: code quality :recycle:, build system :wrench:, PCP
