Repository htop-dev/htop, pull requests merged in 2021-01, with the labels that each got.

#437 Show arrow indicating order of sorted process column
  CRT.c
  CRT.h
  ProcessList.c
Labels: enhancement

#455 InfoScreen: fix uncontrolled format string
  InfoScreen.c
Labels: bug :bug:

#458 CI: enable format attributes in ncurses headers
  .github/workflows/ci.yml
  CRT.c
Labels: build system :wrench:, code quality :recycle:

#457 Revert color change on LightTerminal
  CRT.c
Labels: bug :bug:

#454 Drop usage of formatted error messages from <err.h>
  darwin/DarwinProcessList.c
  dragonflybsd/DragonFlyBSDProcessList.c
  freebsd/FreeBSDProcessList.c
  openbsd/OpenBSDProcessList.c
  solaris/SolarisProcessList.c
Labels: FreeBSD :japanese_ogre:, MacOS :green_apple:, code quality :recycle:, enhancement

#463 Exit follow mode cleanly after followed process dies
  ProcessList.c
Labels: bug :bug:

#461 Linux: use correct column alignment for wide process commands
  Process.c
  Process.h
  RichString.c
  dragonflybsd/DragonFlyBSDProcess.c
  freebsd/FreeBSDProcess.c
  freebsd/FreeBSDProcessList.c
  linux/LinuxProcess.c
  solaris/SolarisProcess.c
Labels: FreeBSD :japanese_ogre:, Linux :penguin:, bug :bug:

#465 Fix white text in the Light Terminal colour scheme
  CRT.c
Labels: enhancement

#79 Add option to drop Linux capabilities
  .github/workflows/ci.yml
  configure.ac
  htop.1.in
  htop.c
Labels: needs-discussion :thinking:

#453 Linux: Add SwapCached to the swap meter
  Action.c
  CRT.c
  CRT.h
  ProcessList.h
  SwapMeter.c
  dragonflybsd/Platform.c
  freebsd/Platform.c
  linux/LinuxProcessList.c
  linux/Platform.c
  openbsd/Platform.c
  solaris/Platform.c
Labels: Linux :penguin:, enhancement

#482 configure overhaul
  .github/workflows/ci.yml
  Makefile.am
  README
  configure.ac
  linux/LibSensors.c
  linux/SystemdMeter.c
Labels: Linux :penguin:, default change, needs-discussion :thinking:

#493 [#480] SysarchMeter to view kernel version/arch info
  Makefile.am
  SysArchMeter.c
  SysArchMeter.h
  darwin/Platform.c
  dragonflybsd/Platform.c
  freebsd/Platform.c
  linux/Platform.c
  openbsd/Platform.c
  solaris/Platform.c
  unsupported/Platform.c
Labels: needs-rebase, new feature
