Repository htop-dev/htop, pull requests merged in 2022-08, with the labels that each got.

#1031 Fix incorrect processor time of processes on DragonFly BSD
  dragonflybsd/DragonFlyBSDProcessList.c
Labels: enhancement, BSD :blowfish:

#1016 Fix build failure on FreeBSD 10.* due to KERN_PROC_CWD unavailable
  freebsd/FreeBSDProcessList.c
Labels: bug :bug:, FreeBSD :japanese_ogre:

#900 linux/SystemdMeter: use warning for some states
  linux/SystemdMeter.c
Labels: Linux :penguin:

#1067 configure: support ceil builtin
  configure.ac
Labels: build system :wrench:

#1068 Document idle process state
  htop.1.in
Labels: documentation :open_book:

#1066 Linux: support openat() without readlinkat()
  Compat.c
  Compat.h
  linux/LinuxProcessList.c
Labels: bug :bug:, Linux :penguin:

#1069 Update CI
  .github/workflows/ci.yml
Labels: build system :wrench:

#1063 Restore non mouse support
  CRT.c
  CRT.h
  CommandLine.c
Labels: bug :bug:, build system :wrench:

#1056 Optimize images to reduce filesize
  docs/images/screenshot.png
  htop.png
Labels: documentation :open_book:
