Repository htop-dev/htop, pull requests merged in 2022-10, with the labels that each got.

#1098 Include automake for Debian/Ubuntu
  README
Labels: documentation :open_book:, build system :wrench:, Hacktoberfest, Linux :penguin:

#1099 Clarify M_TRS/M_DRS columns
  linux/LinuxProcess.c
Labels: enhancement, Hacktoberfest, Linux :penguin:

#1113 GH: add dependabot for GitHub actions dependencies
  .github/dependabot.yml
Labels: build system :wrench:

#1109 Reject unsupported non-option command line arguments
  CommandLine.c
Labels: enhancement

#1111 CI: add GitHub CodeQL action
  .github/workflows/codeql-analysis.yml
Labels: code quality :recycle:, build system :wrench:

#1115 Check for action flags correctly
  MainPanel.c
Labels: bug :bug:

#1110 Toggle the header meters with pound key
  Action.c
  Action.h
  CommandLine.c
  Panel.c
  ScreenManager.c
  ScreenManager.h
Labels: enhancement, new feature

#1117 Do not render a margin around the header if there are any meters
  Header.c
Labels: enhancement

#1121 Update the panel header when changing to another tab
  Action.c
Labels: bug :bug:
