Repository htop-dev/htop, pull requests merged in 2022-01, with the labels that each got.

#917 Fix typo
  htop.1.in
Labels: documentation :open_book:, code quality :recycle:

#916 Fix out of boundary writes in XUtils
  XUtils.c
  XUtils.h
Labels: bug :bug:

#919 Help: Linux swap consistency
  Action.c
Labels: enhancement

#923 FreeBSD: Add support for showing process emulation
  freebsd/FreeBSDProcess.c
  freebsd/FreeBSDProcess.h
  freebsd/FreeBSDProcessList.c
  freebsd/ProcessField.h
Labels: FreeBSD :japanese_ogre:, new feature
