Repository htop-dev/htop, pull requests merged in 2022-06, with the labels that each got.

#1035 Update changelog in preparation for htop-3.2.1 release
  ChangeLog
  configure.ac
Labels: documentation :open_book:, build system :wrench:

#1037 Prevent null pointer dereference on early error
  CRT.c
Labels: bug :bug:

#1045 Fix format specifier warning on 32 bit
  OpenFilesScreen.c
Labels: code quality :recycle:, Linux :penguin:, MacOS :green_apple:
