Repository htop-dev/htop, pull requests merged in 2022-05, with the labels that each got.

#939 ProcessList: fix quadratic process removal when scanning
  Process.c
  Process.h
  ProcessList.c
  Vector.c
  Vector.h
Labels: enhancement

#994 Remove redundant sscanf calls (in (s)scanf a blank validates _zero_ or more whitespace)
  linux/LinuxProcessList.c
Labels: enhancement, code quality :recycle:

#999 Hashtable: fix handling of NULL pointer in Hashtable_dump
  Hashtable.c
Labels: bug :bug:, code quality :recycle:

#1000 Fix Solaris / OmniOS build
  SignalsPanel.c
  SignalsPanel.h
Labels: build system :wrench:, Solaris

#1004 Fix check "whether running in an LXC container"
  linux/Platform.c
Labels: bug :bug:, Linux :penguin:

#1007 Fix heap buffer overflow in Vector_compact
  Vector.c
Labels: bug :bug:, security :police_officer:

#995 LXC: Limit CPU count to what is given in /proc/cpuinfo despite the container seeing the real host CPUs
  linux/LinuxProcessList.c
  linux/Platform.h
Labels: bug :bug:, Linux :penguin:

#1021 fix typo (dist -> disk)
  Action.c
Labels: code quality :recycle:

#1009 Fix process time scaling error on Solaris
  solaris/SolarisProcessList.c
Labels: bug :bug:, Solaris

#996 Add some headers in the Setup -> Display options panel
  DisplayOptionsPanel.c
  OptionItem.c
  OptionItem.h
Labels: enhancement

#1022 Fix all_branches_collapsed setting
  Action.c
  ProcessList.c
Labels: bug :bug:

#1030 Restore functionality of stripExeFromCmdline setting
  Process.c
Labels: bug :bug:, help wanted
