Repository htop-dev/htop, pull requests merged in 2022-04, with the labels that each got.

#965 Linux: fix crash in LXD
  linux/LinuxProcessList.c
Labels: bug :bug:, Linux :penguin:

#786 Do not leave empty last column in header
  Header.c
  Meter.c
Labels: bug :bug:

#969 configure.ac: fix static build with hwloc
  configure.ac
Labels: bug :bug:, build system :wrench:

#971 Fix a compile warning: comparison of unsigned enum expression < 0 is …
  HeaderLayout.h
Labels: code quality :recycle:, build system :wrench:

#962 Improve MainPanel Label on active inc filter (Filter <-> FILTER)
  CommandLine.c
  MainPanel.c
  MainPanel.h
Labels: enhancement

#976 README: Add macOS build dependency install command
  README
Labels: documentation :open_book:, build system :wrench:, MacOS :green_apple:

#931 build: use AC_CANONICAL_HOST, not AC_CANONICAL_TARGET
  configure.ac
Labels: build system :wrench:

#985 Fix typo
  linux/LinuxProcessList.c
Labels: code quality :recycle:

#986 FreeBSD: free emulation string
  freebsd/FreeBSDProcess.c
Labels: enhancement, code quality :recycle:

#984 Document screen tab switching (TAB, Shift-TAB keys)
  Action.c
  htop.1.in
Labels: documentation :open_book:
