Repository htop-dev/htop, pull requests merged in 2023-11, with the labels that each got.

#1322 Permit zero 'total' in bar meter mode; remove assertion
  Meter.c
Labels: enhancement

#1325 Rewrite Row_printTime() with various improvements
  Row.c
Labels: enhancement

#1309 Write configuration to temporary file first
  Settings.c
Labels: enhancement, code quality :recycle:

#1326 Meter.c minor code improvements
  Meter.c
Labels: code quality :recycle:

#1329 Shorten podman/libpod container IDs to 12 characters
  linux/CGroupUtils.c
Labels: enhancement, Linux :penguin:

#1336 Linux + PCP: Add private memory size column
  linux/LinuxProcess.c
  linux/LinuxProcess.h
  linux/LinuxProcessTable.c
  linux/ProcessField.h
  pcp/PCPProcess.c
  pcp/PCPProcess.h
  pcp/PCPProcessTable.c
  pcp/ProcessField.h
Labels: Linux :penguin:, new feature, PCP
