Repository htop-dev/htop, pull requests merged in 2023-04, with the labels that each got.

#1189 Rework some methods of Vector
  Vector.c
Labels: enhancement, code quality :recycle:

#1220 configure: restore hwloc support
  configure.ac
Labels: bug :bug:, build system :wrench:

#1209 Fix scroll relative to followed process
  ProcessList.c
Labels: enhancement

#1228 Add DiskIOMeter support for Darwin
  configure.ac
  darwin/Platform.c
Labels: enhancement, MacOS :green_apple:
