Repository htop-dev/htop, pull requests merged in 2023-02, with the labels that each got.

#637 Add option to shadow path prefixes
  DisplayOptionsPanel.c
  Process.c
  Process.h
  Settings.c
  Settings.h
Labels: new feature

#1183 Changelog update for 3.2.2
  ChangeLog
Labels: documentation :open_book:

#1178 Ignore NaN values when drawing graphs
  Meter.c
Labels: bug :bug:, FreeBSD :japanese_ogre:

#1179 FreeBSD: remove duplicate zfs ARC size subtraction
  freebsd/FreeBSDProcessList.c
Labels: bug :bug:, FreeBSD :japanese_ogre:

#1141 Add a systemd user meter to monitor user units.
  linux/Platform.c
  linux/SystemdMeter.c
  linux/SystemdMeter.h
Labels: enhancement

#1162 Add support for scheduling policies
  Action.c
  Makefile.am
  Process.c
  Process.h
  Scheduling.c
  Scheduling.h
  configure.ac
  freebsd/FreeBSDProcess.c
  freebsd/FreeBSDProcessList.c
  linux/LinuxProcess.c
  linux/LinuxProcessList.c
Labels: new feature

#1072 Linux: highlight username if process has elevated privileges
  CRT.c
  CRT.h
  Process.c
  Process.h
  linux/LinuxProcessList.c
Labels: needs-discussion :thinking:, Linux :penguin:

#1186 Misc cleanup
  ScreenManager.c
  linux/Platform.c
Labels: code quality :recycle:

#1196 Update fdstat_sysctl.c
  generic/fdstat_sysctl.c
Labels: FreeBSD :japanese_ogre:

#1197 Remove LXC special handling for the CPU count
  linux/LinuxProcessList.c
Labels: bug :bug:, Linux :penguin:
