Repository htop-dev/htop, pull requests merged in 2023-10, with the labels that each got.

#1024 Allocate GraphData buffer dynamically
  Meter.c
  Meter.h
Labels: enhancement

#1314 GraphMeterMode_draw() code cleanup
  Meter.c
  Meter.h
Labels: enhancement, code quality :recycle:

#1313 Add nonnull attribute to various String_* functions
  Macros.h
  XUtils.h
  configure.ac
Labels: code quality :recycle:

#913 Incorporate shared memory in bar text
  Action.c
  MemoryMeter.c
  MemoryMeter.h
  darwin/Platform.c
  dragonflybsd/Platform.c
  freebsd/Platform.c
  linux/Platform.c
  netbsd/Platform.c
  openbsd/Platform.c
  solaris/Platform.c
Labels: enhancement

#1315 Record new graph data even when no graph is drawn.
  Meter.c
Labels: bug :bug:
