Repository htop-dev/htop, pull requests merged in 2023-12, with the labels that each got.

#1344 Add note to manual re default memory units of KiB
  htop.1.in
Labels: documentation :open_book:, enhancement

#1350 Meter: use correct unicode characters for digit '9'
  Meter.c
Labels: bug :bug:

#1349 HeaderLayout: add "3 columns - 40/30/30"
  HeaderLayout.h
Labels: enhancement

#1244 Add NetworkIOMeter support for Darwin
  darwin/Platform.c
Labels: enhancement, MacOS :green_apple:

#1357 Support for "truss" (FreeBSD equivalent of "strace")
  TraceScreen.c
Labels: enhancement, Linux :penguin:, FreeBSD :japanese_ogre:, BSD :blowfish:, Solaris, NetBSD :flags:, OpenBSD :blowfish:, DragonflyBSD :fly:

#1356 Dynamic column width for list of open files
  OpenFilesScreen.c
Labels: bug :bug:, enhancement

#1253 Settings: preserve empty header
  Settings.c
Labels: enhancement

#1333 Shorten docker container IDs to 12 characters
  linux/CGroupUtils.c
Labels: Linux :penguin:
