Repository htop-dev/htop, pull requests merged in 2024-04, with the labels that each got.

#1433 Fix regression from storing monotonic time deltas
  Machine.c
Labels: bug :bug:

#1431 Check for absolute paths in environment variables
  Settings.c
Labels: enhancement, default change

#1434 Properly handle RichString_extendLen when an external buffer already exists
  RichString.c
Labels: bug :bug:, code quality :recycle:

#1438 Work around GCC14 memleak diagnostic
  darwin/DarwinProcess.c
  dragonflybsd/DragonFlyBSDProcess.c
  freebsd/FreeBSDProcess.c
  linux/LinuxProcess.c
  netbsd/NetBSDProcess.c
  openbsd/OpenBSDProcess.c
  pcp/PCPProcess.c
  solaris/SolarisProcess.c
Labels: code quality :recycle:

#1445 BarMeterMode_draw() code formatting adjustment
  Meter.c
Labels: enhancement, code quality :recycle:

#1430 linux: harden terminal parsing
  linux/LinuxProcessTable.c
Labels: enhancement, code quality :recycle:

#1446 CI: Remove Autoconf version number from *BSD jobs
  .github/workflows/ci.yml
Labels: build system :wrench:, FreeBSD :japanese_ogre:, OpenBSD :blowfish:, DragonflyBSD :fly:

#1450 Memory leak when a legacy config file exists
  Settings.c
Labels: bug :bug:, code quality :recycle:

#1437 Avoid writing configuration to non-regular file
  Settings.c
  Settings.h
Labels: enhancement, default change

#1456 Update configure.ac with some m4 magic to add a git commit id...
  configure.ac
Labels: enhancement, build system :wrench:

#1440 GCC14 analyzer fixes
  FunctionBar.c
  FunctionBar.h
  linux/LinuxProcessTable.c
Labels: enhancement, code quality :recycle:, needs-discussion :thinking:

#1464 Update `__STDC_VERSION__` check with C23
  Compat.h
Labels: documentation :open_book:, enhancement, code quality :recycle:, build system :wrench:

#1466 Fix "CPU usage bar" help alignment.
  Action.c
Labels: enhancement
