Repository htop-dev/htop, pull requests merged in 2024-08, with the labels that each got.

#1508 Clamp graph meter values in "double" type
  Meter.c
Labels: enhancement, code quality :recycle:

#1461 Fix and improve NICE on FreeBSD
  Process.c
  Process.h
  freebsd/FreeBSDProcess.c
  freebsd/FreeBSDProcess.h
  freebsd/FreeBSDProcessTable.c
  freebsd/ProcessField.h
Labels: enhancement, FreeBSD :japanese_ogre:

#1509 CI: Fix NetBSD build.
  .github/workflows/ci.yml
Labels: bug :bug:, build system :wrench:, NetBSD :flags:

#1519 Force rebuild of display table after removals
  Table.c
  Table.h
Labels: bug :bug:

#1515 Fix display of CPU utilization on FreeBSD
  freebsd/Platform.c
Labels: bug :bug:, FreeBSD :japanese_ogre:

#1520 Drop unused function Process_rowSetPriority()
  Process.c
  Process.h
Labels: code quality :recycle:
