Repository htop-dev/htop, pull requests merged in 2024-12, with the labels that each got.

#1533 Normalize DiskIOMeter bar by number of disks
  DiskIOMeter.c
  DiskIOMeter.h
  darwin/Platform.c
  dragonflybsd/Platform.c
  freebsd/Platform.c
  linux/Platform.c
  netbsd/Platform.c
  pcp/Metric.h
  pcp/Platform.c
Labels: enhancement

#1549 feat: add sensors for Rockchip RK3566
  linux/LibSensors.c
Labels: enhancement, Linux :penguin:

#1439 darwin: Fix memory metrics support for Apple Silicon (ARM64)
  configure.ac
  darwin/DarwinMachine.c
  darwin/DarwinMachine.h
  darwin/Platform.c
Labels: bug :bug:, MacOS :green_apple:

#1574 ci: Bump BSD versions.
  .github/workflows/ci.yml
Labels: build system :wrench:
