Repository htop-dev/htop, pull requests merged in 2024-01, with the labels that each got.

#1361 Attempt to "Fix" OpenBSD Build (Followup)
  openbsd/OpenBSDMachine.c
  openbsd/OpenBSDProcessTable.c
Labels: bug :bug:, build system :wrench:, OpenBSD :blowfish:

#1366 Linux: use fseek(3)
  linux/LinuxProcess.c
Labels: code quality :recycle:

#1367 Fix static linking with libsystemd
  configure.ac
  linux/SystemdMeter.c
Labels: bug :bug:

#1371 fixes for illumos/Solaris platforms
  solaris/Platform.c
  solaris/SolarisMachine.c
  solaris/SolarisMachine.h
  solaris/SolarisProcess.c
  solaris/SolarisProcess.h
  solaris/SolarisProcessTable.c
Labels: bug :bug:, Solaris

#1372 Fix the display of running tasks
  linux/LinuxMachine.c
Labels: bug :bug:, Linux :penguin:

#1319 CRT: print a warning when exiting on signal
  CRT.c
Labels: enhancement, needs-discussion :thinking:

#1380 Undo too-aggressive code collapsing from tree mode refactoring
  Process.c
Labels: bug :bug:

#1386 Explicitly check sscanf(3) and fscanf(3) return values
  Header.c
  Settings.c
  linux/LinuxMachine.c
  linux/LinuxProcessTable.c
  linux/Platform.c
Labels: code quality :recycle:

#1365 Refactor the cmdline heuristics
  linux/LinuxProcessTable.c
Labels: enhancement, code quality :recycle:, Linux :penguin:

#1392 Disable basename matching for kernel threads
  Process.c
Labels: bug :bug:, Linux :penguin:
