Repository htop-dev/htop, pull requests merged in 2024-03, with the labels that each got.

#1412 Resolve configuration path
  CommandLine.c
  Settings.c
  Settings.h
Labels: documentation :open_book:, enhancement, default change, Linux :penguin:

#1413 Ignore FOCUS_IN and FOCUS_OUT events if these have been activated within xterm
  CRT.c
  CRT.h
  ScreenManager.c
Labels: enhancement

#1417 Fix the compiler name for OpenBSD.
  .github/workflows/ci.yml
Labels: enhancement, build system :wrench:

#1414 ci: bump to LLVM 18 and drop workaround
  .github/workflows/ci.yml
Labels: build system :wrench:

#1423 Simplify expression in Process_updateCPUFieldWidths()
  Process.c
Labels: enhancement, code quality :recycle:

#1394 Linux: Correctly mark trailing offline CPU threads
  linux/LinuxMachine.c
Labels: bug :bug:, Linux :penguin:

#1370 CRT: handle/ignore signals
  CRT.c
Labels: documentation :open_book:, enhancement, needs-discussion :thinking:, default change

#1368 README: swap regular file and symlink
  README
  README.md
Labels: documentation :open_book:, support request
