Repository htop-dev/htop, pull requests merged in 2025-02, with the labels that each got.

#1604 Fix possible buffer OOB access when parsing the stat file for a process
  linux/LinuxProcessTable.c
Labels: bug :bug:, code quality :recycle:, Linux :penguin:

#1607 Fix #1599 DarwinProcess.c compiler warning when debug is enabled
  darwin/DarwinProcess.c
Labels: code quality :recycle:, MacOS :green_apple:

#1610 DisplayOptions: "Inc"/"Dec" operations in the function bar
  AffinityPanel.c
  AvailableColumnsPanel.c
  AvailableMetersPanel.c
  CategoriesPanel.c
  ColorsPanel.c
  ColumnsPanel.c
  DisplayOptionsPanel.c
  DisplayOptionsPanel.h
  HeaderOptionsPanel.c
  MainPanel.c
  MetersPanel.c
  ScreenTabsPanel.c
  ScreensPanel.c
Labels: enhancement

#1614 Remove IOKit / IOMainPort / IOMMasterPort logic
  configure.ac
  darwin/Platform.c
Labels: code quality :recycle:, build system :wrench:, MacOS :green_apple:

#1615 Make Dec and Inc consistent on F7 and F8 as per the main panel
  DisplayOptionsPanel.c
Labels: enhancement

#1617 darwin: not every process should be in running state (#1611)
  darwin/DarwinProcess.c
  darwin/DarwinProcessTable.c
Labels: enhancement, MacOS :green_apple:

#1623 darwin: nanoseconds to centi-seconds minor improvement
  darwin/DarwinProcess.c
Labels: code quality :recycle:, MacOS :green_apple:
