Repository htop-dev/htop, pull requests merged in 2025-04, with the labels that each got.

#1661 NetworkIOMeter: Always zero the NetworkIOData buffer before updating
  NetworkIOMeter.c
  freebsd/Platform.c
  linux/Platform.c
  pcp/Platform.c
Labels: enhancement, Solaris, NetBSD :flags:, OpenBSD :blowfish:, DragonflyBSD :fly:

#1660 build: Ensure strchrnul() is available in header (fixes macOS build)
  configure.ac
Labels: enhancement, build system :wrench:, MacOS :green_apple:

#1663 PCP: Remove semicolons from empty statements
  pcp/PCPDynamicMeter.c
  pcp/PCPDynamicScreen.c
Labels: code quality :recycle:, PCP

#1672 openbsd: Document sysctl indices for ACPI battery & AC code
  openbsd/Platform.c
Labels: documentation :open_book:, code quality :recycle:, OpenBSD :blowfish:

#1649 Meter: Prevent integer overflow on x positions
  CPUMeter.c
  MemorySwapMeter.c
  Meter.c
Labels: code quality :recycle:

#1675 Cleanup unsigned
  Scheduling.c
  darwin/DarwinMachine.c
  linux/HugePageMeter.c
  linux/LinuxMachine.c
Labels: code quality :recycle:, Linux :penguin:, MacOS :green_apple:

#1677 Meter: Reset attributes after drawing bar borders
  Meter.c
Labels: bug :bug:

#1682 Make the physicalID default to 0 because old Intel processors only have that
  linux/LibSensors.c
Labels: enhancement

#1683 Avoid passing NULL to strlen when updating procComm
  darwin/DarwinProcess.c
Labels: bug :bug:, MacOS :green_apple:

#1669 Some '-Wshorten-64-to-32' warning fixes
  AffinityPanel.c
  IncSet.h
  Meter.c
  Panel.c
  Process.c
  Row.c
  Settings.c
  generic/gettime.c
  linux/LinuxProcess.c
  openbsd/Platform.c
Labels: code quality :recycle:

#1671 Added COLORSCHEME_NORD
  CRT.c
  CRT.h
  ColorsPanel.c
Labels: enhancement

#1688 Implement fallback for old MacOS versions
  configure.ac
  darwin/DarwinProcess.c
Labels: bug :bug:, MacOS :green_apple:
