Repository htop-dev/htop, pull requests merged in 2025-03, with the labels that each got.

#1627 Fix build for unsupported platform
  unsupported/UnsupportedProcess.h
  unsupported/UnsupportedProcessTable.c
Labels: bug :bug:, code quality :recycle:

#1628 Build unsupported
  .github/workflows/ci.yml
  configure.ac
  unsupported/UnsupportedMachine.c
Labels: code quality :recycle:, build system :wrench:

#1630 Handle when there's no CPUMeter to display
  CPUMeter.c
Labels: bug :bug:

#1631 Update pcp-htop configurations to use libbpf over BCC
  pcp-htop.5.in
  pcp/columns/tcp
  pcp/columns/udp
Labels: documentation :open_book:, PCP

#1634 Fix missing header for native curses build in NetBSD.
  Settings.c
Labels: bug :bug:, build system :wrench:, NetBSD :flags:

#1633 Prevent assertion error in Machine_scanTables()
  Machine.c
Labels: bug :bug:, code quality :recycle:

#1641 Support for stuck processes on macOS
  darwin/DarwinProcess.c
Labels: enhancement, MacOS :green_apple:

#1652 man: document the --user work for self...
  htop.1.in
Labels: documentation :open_book:, enhancement

#1635 CI: Update LLVM repo and use ubuntu-latest for building "unsupported" htop
  .github/workflows/ci.yml
Labels: build system :wrench:
