Repository htop-dev/htop, pull requests merged in 2025-06, with the labels that each got.

#1716 Handle special cases for CPU frequency data in /proc/cpuinfo
  linux/LinuxMachine.c
Labels: enhancement, Linux :penguin:

#1715 Make empty --filter= command line arguments invalid
  CommandLine.c
Labels: enhancement

#1588 Use size_t for Process offset values
  Process.c
  Process.h
  darwin/DarwinProcess.c
  dragonflybsd/DragonFlyBSDProcessTable.c
  freebsd/FreeBSDProcessTable.c
  linux/LinuxProcessTable.c
  netbsd/NetBSDProcessTable.c
  openbsd/OpenBSDProcessTable.c
  pcp/PCPProcessTable.c
Labels: enhancement, code quality :recycle:, Linux :penguin:, FreeBSD :japanese_ogre:, MacOS :green_apple:, BSD :blowfish:, PCP, NetBSD :flags:, OpenBSD :blowfish:, DragonflyBSD :fly:

#1714 Make Infoscreen also show uppercase FILTER when filtering (F4) is active
  InfoScreen.c
Labels: enhancement

#1702 Align structures 8 byte for 64-bit platforms
  DynamicMeter.c
  DynamicScreen.c
  FunctionBar.h
  IncSet.h
  ScreenManager.h
  TraceScreen.h
  linux/LinuxProcessTable.h
Labels: enhancement, code quality :recycle:

#1723 FreeBSD: Update the internal priority reference point
  freebsd/FreeBSDProcessTable.c
  freebsd/FreeBSDProcessTable.h
Labels: enhancement, FreeBSD :japanese_ogre:

#1729 Fix buffer overflow in DisplayOptionsPanel
  DisplayOptionsPanel.c
Labels: bug :bug:

#1730 Make the Panel items actually match what receives a mouse click
  DisplayOptionsPanel.c
Labels: bug :bug:

#1733 Use default key list for DisplayOptions "Dec/Inc" function bar
  DisplayOptionsPanel.c
Labels: enhancement
